FRAMES_NAMES = {b'TALB', b'TPE1', b'COMM', b'TRCK', b'TYER', b'TXXX',
                b'TCON', b'TIT2', b'TSOA', b'TPE2', b'TSO2', b'TSOP',
                b'TBPM', b'TCMP', b'TCOM', b'TSOC', b'TPE3', b'TIT1',
                b'TCOP', b'TPOS', b'TENC', b'TSSE', b'TOWN', b'TFLT',
                b'GRP1', b'TKEY', b'IPLS', b'TSRC', b'TLAN', b'TLEN',
                b'TEXT', b'TMED', b'TPE4', b'MVNM', b'MVIN', b'MVIN',
                b'TRSO', b'TRSN', b'TOAL', b'TOPE', b'TOFN', b'TOLY',
                b'TORY', b'PCST', b'TCAT', b'TDES', b'TGID', b'TKWD',
                b'WFED', b'POPM', b'TPUB', b'POPM', b'POPM', b'TDRL',
                b'TIT3', b'TSOT', b'USLT', b'WXXX', b'WOAR', b'WOAF',
                b'WOAS', b'WCOM', b'WCOP', b'WPAY', b'WPUB', b'WORS'}
